version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  h2o:
    build:
      context: ./h2oai
      dockerfile: Dockerfile
    ports:
      - "54321:54321"
      - "54322:54322"
      - "54323:54323"
  
  supabase:
    image: supabase/postgres:0.14.0
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  rancher:
    image: rancher/rancher:latest
    restart: always
    ports:
    - "80:80/tcp"
    - "443:443/tcp"
    volumes:
    - "rancher-data:/var/lib/rancher"
    privileged: true

  tensorboard:
    build:
      context: ./tensorboard
      dockerfile: Dockerfile
    ports:
      - "6006:6006"

volumes:
  jenkins_home:
  supabase_data:
  rancher-data:
